name: Build & publish ECS/Fargate worker image to ECR

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: 'Branch ref to checkout'
        type: string
        default: null
    secrets:
      TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      - name: Show git ref
        run: |
            echo ${{ github.ref }}
            echo ${{ github.event.pull_request.head.sha }}
            echo ${{ github.sha }}

      - name: "Hello World"
        run: echo "${{ github.sha }}" && echo "${{ secrets.TOKEN }}"
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18.x
      - name: Run console log
        run: npm test