name: Run tests from fork
on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, labeled, reopened]

jobs:
  is-collaborator:
    runs-on: ubuntu-latest
    steps:
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check User Permission
        if: steps.checkAccess.outputs.require-result == 'false'
        run: |
          echo "${{ github.actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          exit 1

  do-something:
    if: contains( github.event.pull_request.labels.*.name, 'run-aws-tests' )
    needs: is-collaborator
    permissions:
      id-token: write
      contents: read
    secrets:
      TOKEN: ${{ secrets.NOT_A_SECRET }}
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    uses: ./.github/workflows/docker-ecr.yml

  demo:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'run-aws-tests' )
    needs: do-something
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # This is dangerous without the first access check
      - name: Run tests
        run: |
          if [[ "x${{ secrets.NOT_A_SECRET }}" == "xval" ]]; then
            echo "Access to secrets"
          else
            echo "No access to secrets"
            exit 1
          fi
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18.x
      - name: Run console log
        run: npm test